fixup! fixup! Add script to set 'report.url' and 'web.base.url'

diff --git a/start-entrypoint.d/001_set_report_url b/start-entrypoint.d/001_set_report_url
--- a/start-entrypoint.d/001_set_report_url
+++ b/start-entrypoint.d/001_set_report_url
@@ -1,15 +1,15 @@
 # Copyright 2016-2022 Camptocamp SA (http://www.camptocamp.com)
 #!/bin/bash
 
-if ! command -v psql &> /dev/null
-then
-    echo "psql could not be found, ignoring set_report_url script"
-    exit
-fi
-
 DOMAIN="${ODOO_REPORT_URL}"
 
 if [ -n "$DOMAIN" ]; then
+
+  if ! command -v psql &> /dev/null
+  then
+      echo "Command 'psql' could not be found, ignoring script"
+      exit
+  fi
 
   if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
   then
